version: '3.1'
services:
  mongo:
    image: mongo:6
    container_name: gridfs
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${INITDB_DATABASE}
      MONGO_INITDB_USER: ${INITDB_USER}
      MONGO_INITDB_USER_PASSWORD: ${INITDB_USER_PASSWORD}

