version: '3.1'
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes: 
      - ./data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}